/* eslint-disable no-var */
/**
 * @see https://developer.ones.cn/docs/guide/advanced/storage
 * @summary ones.d.ts is generated by `op format` cli commands.
 * DO NOT MODIFY MANUALLY
 */
declare var ONESEntities: {
    dcp_base_config: {
        attributes: {
            key?: string;
            value?: string;
        };
        indexes: null;
    };
    dcp_phase_template: {
        attributes: {
            phase_code?: string;
            phase_name?: string;
            resolution_options?: string;
            resolution_template?: string;
            sort_order?: number;
            review_type?: string;
            dependencies?: string;
        };
        indexes: null;
    };
    dcp_material_template: {
        attributes: {
            material_name?: string;
            applicable_phases?: string;
            required?: boolean;
            responsible_role?: string;
            sort_order?: number;
            review_type?: string;
        };
        indexes: null;
    };
    dcp_indicator_template: {
        attributes: {
            indicator_name?: string;
            applicable_phases?: string;
            unit?: string;
            threshold_type?: string;
            yellow_threshold?: number;
            red_threshold?: number;
            sort_order?: number;
            review_type?: string;
        };
        indexes: null;
    };
    dcp_reviewer_role: {
        attributes: {
            role_name?: string;
            must_vote?: boolean;
            has_veto?: boolean;
            sort_order?: number;
            review_type?: string;
        };
        indexes: null;
    };
    dcp_review: {
        attributes: {
            review_uuid?: string;
            project_uuid?: string;
            phase_code?: string;
            review_title?: string;
            meeting_time?: number;
            status?: string;
            creator_uuid?: string;
            created_at?: number;
            updated_at?: number;
            review_number?: string;
            reviewer_profile_id?: string;
            reviewer_profile_name?: string;
            reviewer_profile_snapshot_json?: string;
            reviewer_binding_snapshot_json?: string;
            reviewer_role_assignments_snapshot_json?: string;
            reviewers_json?: string;
            checklist_json?: string;
            review_type?: string;
            review_state?: string;
            round_no?: number;
            round_state?: string;
            state_history_json?: string;
            resolution_rule_json?: string;
            config_frozen_at?: number;
            config_version_note?: string;
            role_templates_json?: string;
            checklist_templates_json?: string;
            bound_profile_id?: string;
            profile_snapshot_json?: string;
        };
        indexes: null;
    };
    dcp_review_material: {
        attributes: {
            review_uuid?: string;
            template_id?: string;
            submit_status?: string;
            notes?: string;
            file_name?: string;
            file_data?: string;
            file_size?: number;
            uploaded_at?: number;
            updated_by?: string;
            updated_at?: number;
            round_no?: number;
            material_name?: string;
            required?: number;
            responsible_role?: string;
            sort_order?: number;
            attachments_json?: string;
        };
        indexes: null;
    };
    dcp_review_indicator: {
        attributes: {
            review_uuid?: string;
            template_id?: string;
            current_value?: number;
            notes?: string;
            risk_color?: string;
            updated_by?: string;
            updated_at?: number;
            round_no?: number;
            indicator_name?: string;
            threshold_type?: string;
            yellow_threshold?: number;
            red_threshold?: number;
            sort_order?: number;
        };
        indexes: null;
    };
    dcp_review_reviewer: {
        attributes: {
            review_uuid?: string;
            reviewer_uuid?: string;
            role_name?: string;
            selection_mode?: string;
            default_reviewer_uuid?: string;
            candidate_uuids_json?: string;
            conclusion?: string;
            risk_level?: string;
            opinion_summary?: string;
            submitted_at?: number;
            round_no?: number;
        };
        indexes: null;
    };
    dcp_linked_issue: {
        attributes: {
            review_uuid?: string;
            issue_uuid?: string;
            issue_number?: string;
            issue_title?: string;
            issue_type?: string;
            issue_status?: string;
            issue_status_id?: string;
            issue_status_category?: string;
            issue_status_is_done?: boolean;
            issue_status_verification?: string;
            issue_status_source?: string;
            issue_status_checked_at?: number;
            issue_status_error?: string;
            linked_by?: string;
            linked_by_name?: string;
            linked_at?: number;
            link_type?: string;
            round_no?: number;
            locked?: string;
            locked_at?: number;
            locked_by?: string;
        };
        indexes: null;
    };
    dcp_phase_guard: {
        attributes: {
            guard_key?: string;
            project_uuid?: string;
            phase_code?: string;
            review_type?: string;
            review_uuid?: string;
            guard_state?: string;
            claimed_at?: number;
            released_at?: number;
        };
        indexes: null;
    };
    dcp_resolution: {
        attributes: {
            review_uuid?: string;
            resolution_result?: string;
            final_conclusion?: string;
            resolution_body?: string;
            generated_by?: string;
            generated_at?: number;
            condition_notes?: string;
            based_on_votes?: string;
            snapshot_number?: string;
            published_by?: string;
            published_by_name?: string;
            published_at?: number;
            round_no?: number;
            snapshot_indicators?: string;
            snapshot_checklist?: string;
            snapshot_issues?: string;
        };
        indexes: null;
    };
    dcp_supplement: {
        attributes: {
            review_uuid?: string;
            note_type?: string;
            note_title?: string;
            note_content?: string;
            submitted_by?: string;
            submitted_at?: number;
        };
        indexes: null;
    };
    dcp_audit_log: {
        attributes: {
            review_uuid?: string;
            timestamp?: number;
            operator_uuid?: string;
            action?: string;
            target?: string;
            detail?: string;
            result?: string;
        };
        indexes: null;
    };
    dcp_checklist_item: {
        attributes: {
            phase_code?: string;
            role_name?: string;
            item_text?: string;
            sort_order?: number;
            review_type?: string;
        };
        indexes: null;
    };
    dcp_checklist_result: {
        attributes: {
            review_uuid?: string;
            template_id?: string;
            status?: string;
            checked_by?: string;
            checked_at?: number;
        };
        indexes: null;
    };
    dcp_reviewer_profile: {
        attributes: {
            profile_name?: string;
            review_type?: string;
            description?: string;
            role_assignments_json?: string;
            created_by?: string;
            created_at?: number;
            updated_at?: number;
        };
        indexes: null;
    };
    dcp_project_binding: {
        attributes: {
            project_uuid?: string;
            profile_id?: string;
            review_type?: string;
            created_by?: string;
            created_at?: number;
        };
        indexes: null;
    };
};
